import tkinter
root = tkinter.Tk()
root.title("BlackJack")
Blackjack = tkinter.Label(root, text="BlackJack")
Blackjack.grid(row=1, column=2)
explanation = tkinter.Label(root, text="You will be given 2 cards on random and having an option to draw another card. "
                                       "You win if your cards are higher than the dealers and less than 21")
explanation.grid(row=2, column=2)
hit = tkinter.Button(root, text="hit")
hit.grid(row=3, column=2)
stay = tkinter.Button(root, text="stay")
stay.grid(row=4, column=2)
img = tkinter.PhotoImage(file="Try1.png")
panel = tkinter.Label(root, image=img)
panel.grid(row=3, column=1)
img1 = tkinter.PhotoImage(file="Try2.png")
panel1 = tkinter.Label(root, image=img)
panel1.grid(row=3, column=3)
user_total = tkinter.Label(root, text="Your total is:")
user_total.grid(row=5, column=1)
dealer_total = tkinter.Label(root, text="Dealer total is:")
dealer_total.grid(row=5, column=3)
root.mainloop()
